apiVersion: v1
kind: ConfigMap
metadata:
  name: devzone-configmap
  namespace: default
data:
  postgres_host: devzone-postgres-svc
  postgres_port: "5432"
  postgres_database: devzonedb
---
apiVersion: v1
kind: Secret
metadata:
  name: devzone-secrets
type: Opaque
data:
  postgres_username: c2l2YQ== # siva
  postgres_password: c2l2YWxhYnM= # sivalabs
