version: '3.8'
services:

  elasticsearch:
    image: elasticsearch:8.5.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xmx2048m -Xms2048m"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  logstash:
    image: logstash:8.5.1
    container_name: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./elk:/etc/logstash/conf.d
      - ../logs/:/logs/
    ports:
      - "15000:5000"
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.5.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata1:
    driver: local
