# Default values for postgresql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "17-alpine"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5432
  targetPort: 5432

postgresUsername: postgres
postgresPassword: postgres
postgresDatabase: appdb
postgresPort: 5432
