apiVersion: 1

deleteDatasources:
    -   name: Prometheus
    -   name: Tempo
    -   name: Loki

datasources:
    -   name: Prometheus
        type: prometheus
        uid: prometheus-sivalabs
        access: proxy
        orgId: 1
        url: http://prometheus:9090
        basicAuth: false
        isDefault: false
        version: 1
        editable: true
        jsonData:
            httpMethod: POST
            exemplarTraceIdDestinations:
                -   name: trace_id
                    datasourceUid: tempo-sivalabs

    -   name: Loki
        type: loki
        uid: loki-sivalabs
        access: proxy
        orgId: 1
        url: http://loki:3100
        basicAuth: false
        isDefault: true
        version: 1
        editable: true
        jsonData:
            derivedFields:
                -   datasourceUid: tempo-sivalabs
                    matcherRegex: \[.+,(.+?),
                    name: TraceID
                    url: $${__value.raw}

    -   name: Tempo
        type: tempo
        uid: tempo-sivalabs
        access: proxy
        orgId: 1
        url: http://tempo:3100
        basicAuth: false
        isDefault: false
        version: 1
        editable: true
        jsonData:
            httpMethod: GET
            tracesToLogs:
                datasourceUid: 'loki-sivalabs'
                tags: [ 'instance', 'pod', 'namespace', 'hostname' ]
                mappedTags: [ { key: 'service.name', value: 'container' } ]
                mapTagNamesEnabled: true
                spanStartTimeShift: '-1h'
                spanEndTimeShift: '1h'
                filterByTraceID: true
                filterBySpanID: false
                lokiSearch: true
            serviceMap:
                datasourceUid: 'prometheus-sivalabs'
            search:
                hide: false
            nodeGraph:
                enabled: true

